apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-app
  name: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - image: java-app:local
        name: java-app
        args:
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseCGroupMemoryLimitForHeap
        - -XX:+PrintFlagsFinal
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        readinessProbe:
          exec:
            command:
            - wget
            - -O readineness
            - http://localhost:8080/
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 6
        livenessProbe:
          exec:
            command:
            - wget
            - -O liveness
            - http://localhost:8080/
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-app
  name: java-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-app

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: java-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /java-app
        backend:
          serviceName: java-app
          servicePort: 80
